### PR TITLE
week 1 homework 3 and 4

### PR DESCRIPTION
**Pull request by AliceYunanTang**

### CODE REVIEW

**Comment by AliceYunanTang** [comment]
hi

**Comment by AliceYunanTang** [comment]
hi

**Comment by AliceYunanTang** [comment]
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible; 8

Was there anything that you struggled with?;  No
Is there anything that you'd like some further information on?; No
Roughly how long did it take? 6 hours

**Comment by matedge** [comment]
Great work Alice, you obviously have a clear understanding of the concepts we have covered. Amazing!

**Pull request merged**
