### PR TITLE
Week1 Homework One & Two

### PR DESCRIPTION
**Pull request by maxbausher**
IMPORTANT: In the pull request comment, tell me the following:
A. How difficult did you find this (out of 10)? 
    - 8/10
B. Was there anything that you struggled with?
    - Struggled with a few of the string.js challenges (namely fixStart & notBad)
C. Is there anything that you'd like some further information on?
    -  can you stack methods into one line or off one variable?
D. Roughly how long did it take?
    - 5 hours

### CODE REVIEW

**Comment by maxbausher** [comment]
homework for arrays.

IMPORTANT: In the pull request comment, tell me the following:
- How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
     8/10 
- Was there anything that you struggled with?
     The base level of homework was difficult, but do-able. However, the bonus Wheel of 
     fortune got me bogged down, still sorting through it
- Is there anything that you'd like some further information on?
      when to break repeated functionality within a function into another function which is then called 
       inside the original function.
- Roughly how long did it take?
       1 hour for initial homework - wordguesser
       1.5 hours for current status of wheel of fortune bonus challenge.

**Comment by maxbausher** [comment]
IMPORTANT: In the pull request comment, tell me the following:
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
6/10 

Was there anything that you struggled with?
- Sudo code helped a ton today. before starting to touch the keyboard, i spent a good fifteen minutes walking through the homework prompt with a pen and notepad outlining and diagramming in my head what was needed.  became fun, telling the story through javascript as if i was a customer of the bank... breakthrough moment on this one!

Is there anything that you'd like some further information on?
how to parse or grab pieces of predictable responses from a prompt() in a more efficient way.

Roughly how long did it take?
6 -ish hours

**Comment by maxbausher** [comment]
updated homework for bank to include if else statement on withdrawal function to protect against lack of funds.

**Comment by maxbausher** [comment]
Added transfer functionality and prompts to the bank homework

**Comment by matedge** [comment]
Max,

Awesome work bud. Keep up the attitude and determination,  you are kicking major goals!

So glad you had the breakthrough of planning out your problems with sudo code or pen and paper. This is one of the major fundamentals of problem solving and is going to come in handy for this weekends homework and for all your future projects.

Keep breaking your code into smaller challenges so it all becomes easy. You really seem to be grasping this in the past 2 days. 

I have to see that your attitude is amazing and you seem really determined to nail every problem. Great to see.

"when to break repeated functionality within a function into another function which is then called
inside the original function." -     please either tell me you understand this now or come speak to myself or Luke,  mainly so i don't have to get my head around that sentence haha.

**Pull request merged**
