### PR TITLE
MTA 1 line only & bank homework

### PR DESCRIPTION
**Pull request by jonathansee2013**
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
Bank homework was 8 while MTA was 9 for me

Was there anything that you struggled with?;
had a hard time about objects and how to access its properties. still have to learn more about loops and when and when not to use them

Is there anything that you'd like some further information on?;
still need to learn more objects and loops.

Roughly how long did it take?
Bank homework 3 hours and did not finish. MTA, the whole weekend.

### CODE REVIEW

**Comment by jonathansee2013** [comment]
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
7. I enjoyed it though i wish i had more time to learn the concepts to make it better.

Was there anything that you struggled with?;
when to use div class tags

Is there anything that you'd like some further information on?;
floating images, making columns, placing background images

Roughly how long did it take?
more than 3 hours

**Comment by jonathansee2013** [comment]
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
4
Was there anything that you struggled with?;
i could not get my image to float to the left and the text to wrap around it.
Is there anything that you'd like some further information on?;
would like to know more about positioning of images
Roughly how long did it take?
less than 3 hours

**Comment by jonathansee2013** [comment]
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
   6
Was there anything that you struggled with?;
   I struggled to make the cat's image flip and walk back to the left.
Is there anything that you'd like some further information on?;
   Even though it took me a long time to figure it out, I enjoyed playing with the images.
Roughly how long did it take?
  more than 3 hours

**Comment by jonathansee2013** [comment]
How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;
6
Was there anything that you struggled with?;
Even with jQuery, I still could not figure out how to flip the cat's image and make it walk back.
Is there anything that you'd like some further information on?;
functions such as making an image bigger/smaller, revolve, appear, disappear
Roughly how long did it take?
more than 3 hours

**Comment by matedge** [comment]
Good work Jonathan,  As for making an image bigger/smaller, revolve, appear etc. We will be covering a lot of that this afternoon and i will update the gitBook at the end of the day with all the awesome animation functions that jQuery gives us to play with.
Glad you are enjoying the CSS homework, it is rewarding to get instant graphical feedback for your changes and makes you feel like you are building something tangible. 
Keep up the good work. We will be getting a lot more practice with objects to help get your head around them in the coming days. Be sure to ask plenty of questions to help you grasp them. Practice is the best way.

**Pull request merged**
